spring.application.name=oauth_app_authentication_demo

# configuration for the OAuth application
spring.security.oauth2.client.registration.github.client-id=Ov23liAEgzEWzviTCQW1
spring.security.oauth2.client.registration.github.client-secret=a6e5eaac1971159936b1158fe6c55c40893b7e07